'use client';

import { periodList, periodLabel } from '../lib/day';
import { REASON_LEGEND } from '../lib/reasons';

export default function PrintTab({ school, teachers, covers, absences }) {
  const byId = Object.fromEntries(teachers.map((t) => [t.id, t]));
  const absentIds = [...new Set(covers.map((c) => c.absent_teacher_id))];
  const absMap = {};
  const reasonMap = {};
  absences.forEach((a) => {
    absMap[a.teacher_id] = new Set(a.periods);
    reasonMap[a.teacher_id] = a.reason;
  });

  const dateStr = new Date().toLocaleDateString('en-ZA', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });

  if (covers.length === 0) {
    return (
      <section>
        <h2 className="no-print">Print Sheet</h2>
        <div className="empty">Nothing to print yet — generate covers first.</div>
      </section>
    );
  }

  return (
    <section>
      <h2 className="no-print">Print Sheet</h2>
      <p className="sub">
        The corridor wall sheet. Print with the button below (or Ctrl/Cmd+P) —
        it comes out as landscape A4. Sideways scrolling here is screen-only.
      </p>
      <div className="print-actions">
        <button className="btn" onClick={() => window.print()}>🖨 Print / Save as PDF</button>
      </div>

      <div className="sheet">
        <div className="s-head">
          <h1>BATTING — TODAY</h1>
          <div className="s-date">{school.name} · {school.timetable_mode === 'cycle' ? `Day ${school.current_cycle_day} · ` : ''}{dateStr}</div>
        </div>
        <div className="sheet-scroll">
          <table className="print">
            <thead>
              <tr>
                <th style={{ textAlign: 'left', paddingLeft: 12 }}>Absent Teacher</th>
                {periodList(school).map((p) => <th key={p}>{periodLabel(p).toUpperCase()}</th>)}
              </tr>
            </thead>
            <tbody>
              {absentIds.map((aid) => {
                const t = byId[aid];
                return (
                  <tr key={aid}>
                    <td className="absname">
                      {t?.name || '—'}
                      {reasonMap[aid] && <span className="reason-badge">{reasonMap[aid]}</span>}
                    </td>
                    {periodList(school).map((p) => {
                      const c = covers.find((x) => x.absent_teacher_id === aid && x.period === p);
                      const isAbsentThisPeriod = absMap[aid]?.has(p);
                      if (!c || !isAbsentThisPeriod) return <td key={p} className="dash">—</td>;
                      if (!c.cover_teacher_id) return <td key={p} className="office">SEE OFFICE</td>;
                      const cov = byId[c.cover_teacher_id];
                      return (
                        <td key={p}>
                          <span className="room">{c.class_name}</span>
                          <span className="cov">{cov?.name}</span>
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="s-foot">
          <span>Learners: go to the room shown for each lesson.</span>
          <span>Generated by ReliefDesk</span>
        </div>
        <div className="s-legend">{REASON_LEGEND}</div>
      </div>
    </section>
  );
}
