'use client';

export default function PrintTab({ school, teachers, covers, absences }) {
  const byId = Object.fromEntries(teachers.map((t) => [t.id, t]));
  const periods = school.periods_per_day;
  const absentIds = [...new Set(covers.map((c) => c.absent_teacher_id))];
  const absMap = {};
  absences.forEach((a) => (absMap[a.teacher_id] = new Set(a.periods)));

  const dateStr = new Date().toLocaleDateString('en-ZA', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });

  if (covers.length === 0) {
    return (
      <section>
        <h2 className="no-print">Print Sheet</h2>
        <div className="empty">Nothing to print yet — generate covers first.</div>
      </section>
    );
  }

  return (
    <section>
      <h2 className="no-print">Print Sheet</h2>
      <p className="sub">
        The corridor wall sheet. Print with the button below (or Ctrl/Cmd+P) —
        it comes out as landscape A4. Sideways scrolling here is screen-only.
      </p>
      <div className="print-actions">
        <button className="btn" onClick={() => window.print()}>🖨 Print / Save as PDF</button>
      </div>

      <div className="sheet">
        <div className="s-head">
          <h1>TEACHER COVER — TODAY</h1>
          <div className="s-date">{school.name} · {dateStr}</div>
        </div>
        <div className="sheet-scroll">
          <table className="print">
            <thead>
              <tr>
                <th style={{ textAlign: 'left', paddingLeft: 12 }}>Absent Teacher</th>
                {Array.from({ length: periods }, (_, i) => <th key={i}>L{i + 1}</th>)}
              </tr>
            </thead>
            <tbody>
              {absentIds.map((aid) => {
                const t = byId[aid];
                return (
                  <tr key={aid}>
                    <td className="absname">{t?.name || '—'}</td>
                    {Array.from({ length: periods }, (_, i) => {
                      const p = i + 1;
                      const c = covers.find((x) => x.absent_teacher_id === aid && x.period === p);
                      const isAbsentThisPeriod = absMap[aid]?.has(p);
                      if (!c || !isAbsentThisPeriod) return <td key={p} className="dash">—</td>;
                      if (!c.cover_teacher_id) return <td key={p} className="office">SEE OFFICE</td>;
                      const cov = byId[c.cover_teacher_id];
                      return (
                        <td key={p}>
                          <span className="room">{c.room}</span>
                          <span className="cov">{cov?.name}</span>
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="s-foot">
          <span>Learners: go to the room shown for each lesson.</span>
          <span>Generated by ReliefDesk</span>
        </div>
      </div>
    </section>
  );
}
